"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var point_1 = require("./point");
var triangle_1 = require("./triangle");
var vertex1 = new point_1.Point(1, 2);
var vertex2 = new point_1.Point(3, 1);
var vertex3 = new point_1.Point(4, 5);
var myTriangle = new triangle_1.Triangle(vertex1, vertex2, vertex3);
var sidesLength = myTriangle.calculateLengthSides();
console.log(sidesLength);
